spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice_feign_customer
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 8010